// Build one RadioPad frontend surface (desktop | web | mobile).
//
// RadioPad ships one Next.js codebase as three specialised surfaces. Routes
// are organised into App Router route groups whose folder name encodes the
// surface it belongs to:
//   app/(desktop)/…  full reporting product      (Tauri)
//   app/(web)/…      master-admin / platform ops  (browser)
//   app/(mobile)/…   dictation companion          (Capacitor)
//   app/(shared)/…   login / register / account   (every surface)
// (Ungrouped top-level routes also ship on every surface.)
//
// Route groups are invisible in the URL, so `/admin`, `/reports`, `/pair`
// keep their paths. To make each surface *physically* ship only its own
// routes, this script stages the non-target group folders OUT of `app/`
// before `next build` and moves them back afterwards — so e.g. the web bundle
// contains no reporting code at all.
//
// The root route `/` is the desktop reporting dashboard (`app/page.tsx`). It
// is not in a group (so `next dev` — always desktop — renders it directly with
// no redirect flash). For web/mobile builds this script swaps it for a tiny
// redirect stub (web → /admin/users, mobile → /pair), so the dashboard code is
// excluded there too.
//
// All staging is crash-safe: a leftover staged folder/file from an interrupted
// run is restored on the next invocation, and the live build restores in a
// `finally` block.
//
// Next's `output: 'export'` always writes to `out/`; we then move it to a
// stable per-surface directory consumed by each shell:
//   Tauri     → frontendDist ../../frontend/out-desktop
//   Capacitor → webDir       ../frontend/out-mobile
//   Web deploy serves         frontend/out-web
//
// Invoked from package.json as `node scripts/build-surface.mjs <surface>`.

import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { rmSync, renameSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const require = createRequire(import.meta.url);

const SURFACES = new Set(['desktop', 'web', 'mobile']);
const surface = process.argv[2];

if (!SURFACES.has(surface)) {
  console.error(`build-surface: expected one of ${[...SURFACES].join(', ')}, got "${surface ?? ''}"`);
  process.exit(1);
}

const APP_DIR = 'app';
const STAGE_DIR = '.surface-staging';
const GROUP_RE = /^\((.+)\)$/;
const ROOT_PAGE = join(APP_DIR, 'page.tsx');
const ROOT_BAK = join(STAGE_DIR, '__root_page.tsx.bak');

/** Route groups that ship on the active surface: shared + this surface. */
const keepGroups = new Set(['(shared)', `(${surface})`]);

/** Where the root `/` redirects on surfaces that don't own the dashboard.
 *  Mobile lands on the companion pairing home (`/companion`); the existing
 *  `/pair` is the *desktop* device→tenant flow and lives in the desktop group. */
const ROOT_REDIRECT = { web: '/admin/users', mobile: '/companion' };

function rootStub(target) {
  return `'use client';

// GENERATED by scripts/build-surface.mjs for a non-desktop surface build.
// The desktop reporting dashboard (the real app/page.tsx) is excluded here;
// this stub just forwards '/' to the surface's landing route.
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';

export default function SurfaceRootRedirect() {
  const router = useRouter();
  useEffect(() => {
    router.replace(${JSON.stringify(target)});
  }, [router]);
  return null;
}
`;
}

/** Restore anything left in staging by a previous (possibly crashed) run.
 *  Never clobbers or silently drops a staged copy: if a same-named folder has
 *  reappeared in app/ (an inconsistent state), the staged copy is left in place
 *  for inspection rather than deleted. */
function restoreStaged() {
  if (!existsSync(STAGE_DIR)) return;
  // Root page first: drop any stub, then restore the real page.tsx. This moves
  // ROOT_BAK out of STAGE_DIR before the group loop reads the directory.
  if (existsSync(ROOT_BAK)) {
    rmSync(ROOT_PAGE, { force: true });
    renameSync(ROOT_BAK, ROOT_PAGE);
  }
  let allRestored = true;
  for (const name of readdirSync(STAGE_DIR)) {
    const from = join(STAGE_DIR, name);
    const to = join(APP_DIR, name);
    if (existsSync(to)) {
      console.error(`build-surface: cannot restore ${name} — ${to} already exists; leaving ${STAGE_DIR}/${name} in place`);
      allRestored = false;
      continue;
    }
    renameSync(from, to);
  }
  // Only remove the staging dir once every entry is safely back.
  if (allRestored) rmSync(STAGE_DIR, { recursive: true, force: true });
}

/** Move non-target route-group folders out of app/, and swap the root page. */
function stageForSurface() {
  const groups = readdirSync(APP_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && GROUP_RE.test(e.name))
    .map((e) => e.name);
  const excluded = groups.filter((g) => !keepGroups.has(g));
  const swapRoot = surface !== 'desktop' && existsSync(ROOT_PAGE);

  if (excluded.length || swapRoot) mkdirSync(STAGE_DIR, { recursive: true });

  for (const name of excluded) {
    renameSync(join(APP_DIR, name), join(STAGE_DIR, name));
  }
  if (swapRoot) {
    renameSync(ROOT_PAGE, ROOT_BAK);
    writeFileSync(ROOT_PAGE, rootStub(ROOT_REDIRECT[surface] ?? '/'));
  }
  if (excluded.length) console.log(`build-surface: excluding ${excluded.join(', ')} for ${surface}`);
  if (swapRoot) console.log(`build-surface: root / → redirect ${ROOT_REDIRECT[surface]} for ${surface}`);
}

// Always begin from a clean, fully-restored source tree.
restoreStaged();

// Ctrl-C / kill during `next build` would otherwise skip the `finally` below
// and leave route groups staged out + a stub root page on disk. Restore first.
let restoredOnSignal = false;
for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    if (!restoredOnSignal) {
      restoredOnSignal = true;
      try { restoreStaged(); } catch { /* best effort */ }
    }
    process.exit(130);
  });
}

const outDir = `out-${surface}`;
rmSync('out', { recursive: true, force: true });
rmSync(outDir, { recursive: true, force: true });
// Each surface has a *different* route tree, so a `.next` cache from another
// surface leaves stale generated route types (typed-routes stubs for excluded
// pages). Clear it for a correct, self-contained per-surface build.
rmSync('.next', { recursive: true, force: true });

stageForSurface();

let status = 1;
try {
  const nextBin = require.resolve('next/dist/bin/next');
  const result = spawnSync(process.execPath, [nextBin, 'build'], {
    stdio: 'inherit',
    env: { ...process.env, RADIOPAD_SURFACE: surface },
  });
  status = result.status ?? 1;
} finally {
  // Always put the source tree back, even if the build threw.
  restoreStaged();
}

if (status !== 0) process.exit(status);

if (!existsSync('out')) {
  console.error('build-surface: expected next build to produce ./out (is output: "export" set?)');
  process.exit(1);
}

renameSync('out', outDir);
console.log(`build-surface: ${surface} → frontend/${outDir}`);
