// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RadioPad.Infrastructure.Persistence;

#nullable disable

namespace RadioPad.Infrastructure.Migrations
{
    [DbContext(typeof(RadioPadDbContext))]
    [Migration("20260626140000_AddTenantRequireMfa")]
    partial class AddTenantRequireMfa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
            // The canonical snapshot lives in RadioPadDbContextModelSnapshot.cs.
            // EF only consults this method during design-time diffing for the
            // *next* migration; at runtime the [Migration] attribute + Up()/Down()
            // methods are what applies the schema delta.
        }
    }
}
