// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RadioPad.Infrastructure.Persistence;

#nullable disable

namespace RadioPad.Infrastructure.Migrations
{
    [DbContext(typeof(RadioPadDbContext))]
    [Migration("20260503223000_Auth32")]
    partial class Auth32
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
            // The canonical snapshot lives in RadioPadDbContextModelSnapshot.cs
            // which already reflects the post-Auth32 model. EF only consults
            // this method during design-time diffing for the *next* migration;
            // at runtime the [Migration] attribute + Up()/Down() methods are
            // what applies the schema delta.
        }
    }
}
