// One-time asset generator for the marketing site. Run from the marketing/ dir:
//   node scripts/gen-assets.mjs
// - Self-hosts fonts (Fontshare + Google) into public/fonts and regenerates src/styles/fonts.css
// - Downloads placeholder blog covers into src/assets/blog and avatars into public/authors
// - Renders a branded OG image into public/og-default.png via sharp
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

fs.mkdirSync("public/fonts", { recursive: true });
fs.mkdirSync("public/authors", { recursive: true });
fs.mkdirSync("src/assets/blog", { recursive: true });

async function fetchRetry(url, opts = {}, tries = 3) {
  let err;
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url, opts);
      if (!r.ok) throw new Error(`${r.status} ${url}`);
      return r;
    } catch (e) {
      err = e;
    }
  }
  throw err;
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

// ---------- FONTS ----------
function parseFaces(css, latinOnly) {
  const faces = [];
  const re = /(?:\/\*\s*([\w-]+)\s*\*\/\s*)?@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1];
    const body = m[2];
    if (latinOnly && subset && subset !== "latin") continue;
    const fam = (body.match(/font-family:\s*['"]?([^;'"]+)['"]?/) || [])[1]?.trim();
    const weight = (body.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || "400";
    const style = (body.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || "normal";
    const urlm = body.match(/url\(\s*['"]?([^'")]+?\.woff2)['"]?\s*\)/);
    if (fam && urlm) {
      let u = urlm[1].replace(/['"]/g, "").trim();
      if (u.startsWith("//")) u = "https:" + u;
      faces.push({ family: fam, weight, style, url: u });
    }
  }
  return faces;
}

const fontSources = [
  { url: "https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&f[]=general-sans@400,500,600&display=swap" },
  { url: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap", ua: CHROME_UA, latinOnly: true },
];

const chosen = new Map();
for (const s of fontSources) {
  const css = await (await fetchRetry(s.url, { headers: s.ua ? { "User-Agent": s.ua } : {} })).text();
  for (const f of parseFaces(css, s.latinOnly)) {
    const key = `${f.family}|${f.weight}|${f.style}`;
    if (chosen.has(key)) continue;
    const file = `${slug(f.family)}-${f.weight}${f.style === "italic" ? "-italic" : ""}.woff2`;
    const buf = Buffer.from(await (await fetchRetry(f.url)).arrayBuffer());
    fs.writeFileSync(path.join("public/fonts", file), buf);
    chosen.set(key, { ...f, file, size: buf.length });
  }
}

let cssOut = "/* Self-hosted fonts (woff2 in /public/fonts). Generated by scripts/gen-assets.mjs. */\n\n";
for (const f of chosen.values()) {
  cssOut += `@font-face {\n  font-family: "${f.family}";\n  src: url("/fonts/${f.file}") format("woff2");\n  font-weight: ${f.weight};\n  font-style: ${f.style};\n  font-display: swap;\n}\n\n`;
}
fs.writeFileSync("src/styles/fonts.css", cssOut);
console.log(`Fonts: ${chosen.size} files`);
for (const f of chosen.values()) console.log(`  ${f.file} (${f.size} bytes)`);

// ---------- BLOG COVERS ----------
const covers = {
  "why-radiopad-never-signs-a-report": "radiopad-never-signs",
  "encoding-a-chest-ct-rulebook": "radiopad-chest-ct-rulebook",
  "validation-engine-laterality": "radiopad-laterality",
  "exporting-to-fhir": "radiopad-fhir-export",
  "dictation-to-draft": "radiopad-dictation-draft",
  "running-radiopad-on-premise": "radiopad-on-prem",
};
for (const [name, seed] of Object.entries(covers)) {
  const buf = Buffer.from(await (await fetchRetry(`https://picsum.photos/seed/${seed}/1200/675`)).arrayBuffer());
  fs.writeFileSync(path.join("src/assets/blog", `${name}.jpg`), buf);
}
console.log(`Covers: ${Object.keys(covers).length} files`);

// ---------- AUTHOR AVATARS ----------
const avatars = { "priya-nair": 47, "tomas-rieder": 12 };
for (const [name, img] of Object.entries(avatars)) {
  const buf = Buffer.from(await (await fetchRetry(`https://i.pravatar.cc/160?img=${img}`)).arrayBuffer());
  fs.writeFileSync(path.join("public/authors", `${name}.jpg`), buf);
}
console.log(`Avatars: ${Object.keys(avatars).length} files`);

// ---------- TESTIMONIAL AVATARS (self-hosted; placeholder faces) ----------
fs.mkdirSync("public/testimonials", { recursive: true });
const testimonialAvatars = { "priya-nair": 47, "marcus-feld": 15, "sofia-almeida": 32 };
for (const [name, img] of Object.entries(testimonialAvatars)) {
  const buf = Buffer.from(await (await fetchRetry(`https://i.pravatar.cc/96?img=${img}`)).arrayBuffer());
  fs.writeFileSync(path.join("public/testimonials", `${name}.jpg`), buf);
}
console.log(`Testimonial avatars: ${Object.keys(testimonialAvatars).length} files`);

// ---------- OG IMAGE (1200x630) ----------
const og = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#f5f8fb"/>
  <rect x="0" y="0" width="1200" height="10" fill="#2f88d8"/>
  <!-- left: brand + tagline -->
  <g transform="translate(80,120)">
    <rect width="84" height="84" rx="21" fill="#2f88d8"/>
    <path d="M19 42h11l8 19 14-44 8 29h16" fill="none" stroke="#ffffff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
  <text x="180" y="182" font-family="Arial, Helvetica, sans-serif" font-size="60" font-weight="700" fill="#0f1f38">RadioPad</text>
  <text x="82" y="320" font-family="Arial, Helvetica, sans-serif" font-size="46" font-weight="600" fill="#0f1f38">Radiology reports,</text>
  <text x="82" y="378" font-family="Arial, Helvetica, sans-serif" font-size="46" font-weight="600" fill="#40536b">drafted in seconds.</text>
  <text x="82" y="436" font-family="Arial, Helvetica, sans-serif" font-size="46" font-weight="700" fill="#1f6fb8">Signed by you.</text>
  <text x="82" y="556" font-family="Arial, Helvetica, sans-serif" font-size="23" fill="#5d7085">AI-assisted radiology reporting. The radiologist stays the final authority.</text>
  <!-- right: product-preview motif (shapes only, font-independent) -->
  <g transform="translate(720,150)">
    <rect width="400" height="300" rx="20" fill="#ffffff" stroke="#d8e2eb" stroke-width="1.5"/>
    <rect width="400" height="46" rx="20" fill="#f5f8fb"/>
    <rect y="30" width="400" height="16" fill="#f5f8fb"/>
    <circle cx="26" cy="23" r="6" fill="#c43d3d"/>
    <circle cx="46" cy="23" r="6" fill="#a65e00"/>
    <circle cx="66" cy="23" r="6" fill="#11845b"/>
    <line x1="0" y1="46" x2="400" y2="46" stroke="#e7eef4" stroke-width="1.5"/>
    <rect x="28" y="78" width="300" height="11" rx="5.5" fill="#e7eef4"/>
    <rect x="28" y="104" width="240" height="11" rx="5.5" fill="#e7eef4"/>
    <rect x="28" y="130" width="180" height="11" rx="5.5" fill="#bbdcf6"/>
    <rect x="28" y="156" width="270" height="11" rx="5.5" fill="#e7eef4"/>
    <circle cx="34" cy="205" r="5" fill="#c43d3d"/>
    <rect x="50" y="200" width="150" height="9" rx="4.5" fill="#e7eef4"/>
    <circle cx="34" cy="228" r="5" fill="#a65e00"/>
    <rect x="50" y="223" width="120" height="9" rx="4.5" fill="#e7eef4"/>
    <line x1="0" y1="256" x2="400" y2="256" stroke="#e7eef4" stroke-width="1.5"/>
    <rect x="28" y="272" width="126" height="20" rx="10" fill="#dcf2e8"/>
  </g>
</svg>`;
await sharp(Buffer.from(og)).png().toFile("public/og-default.png");
console.log("OG image: public/og-default.png");
console.log("Done.");
